server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always


spring:
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
