server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always


spring:
  r2dbc:
    h2:
      console:
        enabled: true

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
jwt:
  expiration:
    time: 1200000
