version: "3.8"
services:
  zookeeper:
    image: zookeeper:3.6
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.0=zookeeper:2888:3888
    networks:
      online-store:
        ipv4_address: 192.168.0.11
      kafka-zookeeper:
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
      - ./conf/zoo.cfg:/conf/zoo.cfg

  kafka:
    image: confluentinc/cp-kafka:5.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka/data:/var/lib/kafka
    networks:
      online-store:
        ipv4_address: 192.168.0.12
      kafka-zookeeper:

  product-service:
    environment:
      - PRODUCT_PROFILE
    container_name: product-service
    build:
        context: .
        dockerfile: ./product-service/Dockerfile
    image: product-service:latest
    hostname: product-service
    ports:
      - 8091:8091
    networks:
      online-store:
        ipv4_address: 192.168.0.21

  registry-service:
    container_name: registry-service
    build:
      context: .
      dockerfile: ./registry-service/Dockerfile
    image: registry-service:latest
    hostname: registry-service
    ports:
      - 8082:8082
    networks:
      online-store:
        ipv4_address: 192.168.0.3

  config-service:
    container_name: config-service
    build:
      context: .
      dockerfile: ./config-service/Dockerfile
    image: config-service:latest
    hostname: config-service
    ports:
      - 8081:8081
    networks:
      online-store:
        ipv4_address: 192.168.0.2

networks:
  online-store:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"
  kafka-zookeeper:
    driver: bridge
