server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
#    include-stacktrace: on-param

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
#spring:
#  h2:
#    console:
#      enabled: true 
#  r2dbc:
#    url: r2dbc:h2:mem//;
#    name: store
#    username: store 
#    password:
#
#spring:
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/
#    name: store
#    username: postgres
#    password: postgres