logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
        transaction: TRACE

spring:
  cloud:
    gateway:
      httpserver:
        wiretap: true

jwt:
  expiration:
    time: 600000 #10 min
