server:
  port: ${AUTH_SERVICE_PORT:8090}

logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(|%-5p|) %clr(${PID}){magenta} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVICE_NAME:localhost}:${REGISTRY_SERVICE_PORT:8082}/eureka/

spring:
  cloud:
    gateway:
      loadbalancer:
        use404: true
      discovery:
        locator:
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
