server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  cloud:
    gateway:
      loadbalancer:
        use404: true
      discovery:
        locator:
          lower-case-service-id: true
