spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productTestDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: product
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    #properties:
      #hibernate:
        #show_sql: true
        #use_sql_comments: false
        #format_sql: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
