server:
  port: ${PRODUCT_SERVICE_PORT:8091}

logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(|${LOG_LEVEL_PATTERN:-%5p}|) %clr(${PID}){magenta} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVICE_NAME:localhost}:${REGISTRY_SERVICE_PORT:8082}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    #homePageUrl: https://${vcap.application.uris[0]:localhost}/
    #statusPageUrl: https://${vcap.application.uris[0]:localhost}/actuator/info
    #healthCheckUrl: https://${vcap.application.uris[0]:localhost}/actuator/health
    #secureHealthCheckUrl: https://${vcap.application.uris[0]:localhost}/actuator/health
    #hostname: ${PRODUCT_SERVICE_NAME:localhost}

spring:
  sleuth:
    messaging:
      kafka:
        enabled: false
      rabbit:
        enabled: false
    reactor:
      enabled: false
    rxjava:
      schedulers:
        hook:
          enabled: false
    zuul:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

