server:
  port: ${SHOPPING_SERVICE_PORT:8092}

logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(|${LOG_LEVEL_PATTERN:-%5p}|) %clr(${PID}){magenta} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVICE_USER:registry}:${REGISTRY_SERVICE_PASSWORD:registry}@${REGISTRY_SERVICE_NAME:localhost}:${REGISTRY_SERVICE_PORT:8082}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

feign:
  circuitbreaker:
    enabled: true

spring:
  sleuth:
    messaging:
      kafka:
        enabled: false
      rabbit:
        enabled: false
    reactor:
      enabled: false
    rxjava:
      schedulers:
        hook:
          enabled: false
    zuul:
      enabled: false

management:
  cloudfoundry:
    enable: false
  endpoints:
    web:
      base-path: "/${spring.application.name}/actuator"
      exposure:
        include: "*"
        exclude: "env,beans,heapdump,flyway,threaddump,liquidbase,prometheus"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: always
      status:
        order: "fatal,down,out-of-service,unknown,up"
