spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:shoppingDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    platform: h2
    username: shopping
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    #properties:
      #hibernate:
        #show_sql: true
        #use_sql_comments: false
        #format_sql: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
