server:
  port: ${SHOPPING_SERVICE_PORT:8092}

logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(|${LOG_LEVEL_PATTERN:-%5p}|) %clr(${PID}){magenta} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVICE_NAME:localhost}:${REGISTRY_SERVICE_PORT:8082}/eureka/

Feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      base-path: /
      exposure:
        exclude: "*"

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    circuitBreaker:
      requestVolumeThreshold: 10
      errorThresholdPercentage: 80
      sleepWindowInMilliseconds: 6000
  threadpool:
    default:
      coreSize: 15
      mazQueueSize: 5

spring:
  sleuth:
    messaging:
      kafka:
        enabled: false
      rabbit:
        enabled: false
    reactor:
      enabled: false
    rxjava:
      schedulers:
        hook:
          enabled: false
    zuul:
      enabled: false
