server:
  port: 8081
      
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:SirNoob97/OnlineStore.git
          search-paths: config-files
          username: ${GET_USER}
          password: ${GET_PASSWORD}

security:
  user:
    name: root
    password: root
