server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SirNoob97/OnlineStore.git
          search-paths: config-files
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
      discovery:
        enabled: true
        service-id: ${spring.application.name}
    bus:
      enabled: true
      id: ${spring.application.name}
    stream:
      kafka:
        binder:
          zkNodes: ${spring.application.name}:2181
          brokers: ${spring.application.name}:9092
  security:
    user:
      name: root
      password: root
