server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:SirNoob97/OnlineStore.git
          search-paths: config-files
          username: ${GET_USER}
          password: ${GET_PASSWORD}
    fail-fast: true

security:
  user:
    name: root
    password: root
